# Generated by Django 2.2.13 on 2020-06-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200624_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('imagen', models.ImageField(upload_to='galeria/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
