# Generated by Django 2.2.13 on 2020-06-25 06:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to=blog.models.upload_t),
        ),
    ]
