# Generated by Django 2.2.13 on 2020-06-25 17:38

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200625_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenEnGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=blog.models.upload_t)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Galeria')),
            ],
        ),
    ]
